server:
  port: 80


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:springboot_demo}
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}
  mvc:
    view:
      suffix: .html
      prefix: /

openai:
  token: ${OPENAI_TOKEN}
  model: ${OPENAI_MODEL}
  host: ${OPENAI_HOST}
  port: ${OPENAI_PORT}

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
